# Generated by Django 6.1 on 2026-09-06 18:38

import everystep.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everystep', '0002_remove_workflow_claimed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.UUIDField(default=everystep.models.uuid7, editable=False, primary_key=True, serialize=False),
        ),
    ]
