# Generated by Django 6.1 on 2026-09-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everystep', '0003_alter_workflow_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], db_index=True, default='scheduled', max_length=16),
        ),
    ]
