# Generated by Django 6.1 on 2026-09-02 15:54

import d15n.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('args', d15n.models.D15nJSONField(decoder=d15n.models.D15nJSONDecoder, default=list, encoder=d15n.models.D15nJSONEncoder)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=16)),
                ('claimed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('result', d15n.models.D15nJSONField(blank=True, decoder=d15n.models.D15nJSONDecoder, encoder=d15n.models.D15nJSONEncoder, null=True)),
                ('error', d15n.models.D15nJSONField(blank=True, decoder=d15n.models.D15nJSONDecoder, encoder=d15n.models.D15nJSONEncoder, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('name', 'idempotency_key'), name='unique_workflow_per_idempotency_key')],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('args', d15n.models.D15nJSONField(decoder=d15n.models.D15nJSONDecoder, default=list, encoder=d15n.models.D15nJSONEncoder)),
                ('kwargs', d15n.models.D15nJSONField(decoder=d15n.models.D15nJSONDecoder, default=dict, encoder=d15n.models.D15nJSONEncoder)),
                ('status', models.CharField(choices=[('done', 'Done'), ('failed', 'Failed')], max_length=16)),
                ('result', d15n.models.D15nJSONField(blank=True, decoder=d15n.models.D15nJSONDecoder, encoder=d15n.models.D15nJSONEncoder, null=True)),
                ('error', d15n.models.D15nJSONField(blank=True, decoder=d15n.models.D15nJSONDecoder, encoder=d15n.models.D15nJSONEncoder, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='d15n.workflow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workflow', 'step_id'), name='unique_step_per_workflow')],
            },
        ),
    ]
