# Generated by Django 6.1 on 2026-09-03 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d15n', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='claimed_at',
        ),
    ]
